### ISSUE TITLE
Életszimulátorokkal kapcsolatosan

### ISSUE THREAD

**Issue by papp77david** [nbatfai/PRoG#2]
Javasolom a The Sims ág kapcsán egy kis változtatást. 

The Sims élmények esetén (https://github.com/nbatfai/PRoG/blob/main/initial_hack/games/The%20Sims) az "MMORPG élmény"-t illetve az "MMO élményt" kivenném, mivel a 2000-es években a Sims nem tartalmazott online felülethez kapcsolódóan funkciót. Javasolt a The Sims Online (https://en.wikipedia.org/wiki/The_Sims_Online) megemlítése mint további haladási út az ábrában, amely már feltételezhetően tartalmazhatott hasonló élményeket. Ez a  Simshez, illetve a Second Life-hoz  (https://github.com/nbatfai/PRoG/blob/main/initial_hack/games/Second%20Life) szorosan kapcsolódhat.

Továbbá ezen említett három játék esetén javasolom az "Életszimulációs élmény" bevezetését, hiszen ez további kapcsolódási pont lehet.

**Comment by nbatfai** [comment]
A The Sims-ból már reggel töröltem, most az RPG-t visszaírtam bele. Ha leforkolod a projektet, akkor szerintem a saját forkodban tudod kényelmesen akár böngészőből szerkeszteni (kis cerka ikon, "edit this file", a fájl dobozának jobb felső fejrészén) és utána könnyen tudsz pull requestet küldeni.

A Simulated life-ot felvettem a két meglévő 2 játékba. Illetve https://github.com/nbatfai/PRoG/commit/29c1302643a24023c6925d5b3363b0b951c4b913

Lehet eleve ennek mintájára két nyelven adjuk meg az élményeket vagy csak angolul?

**Comment by nbatfai** [comment]
Legyenek angolul az élmények. Visszamenőleg is átírva alkalomadtán, de az újaknál alapértelmezésben. Próbáljunk speciáliabb élményeket, pl. Survivor helyett

Labyrinth survivor (pl. Pac-Man) vagy Open world survivor (pl. Subnautica)

később lehet báfa érdemes szervezni az élményeket is, pl.:

Survivor/Labyrinth
Survivor/Open world
